/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, AudioFile as PrismaAudioFile } from "@prisma/client";
import { AudioFileFindUniqueArgs } from "./AudioFileFindUniqueArgs";
import { AudioFile } from "./AudioFile";
import { AudioFileCreateInput } from "./AudioFileCreateInput";

export class AudioFileServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AudioFileCountArgs, "select">
  ): Promise<number> {
    return this.prisma.audioFile.count(args);
  }

  async audioFiles(
    args: Prisma.AudioFileFindManyArgs
  ): Promise<PrismaAudioFile[]> {
    return this.prisma.audioFile.findMany(args);
  }
  async audioFile(
    args: Prisma.AudioFileFindUniqueArgs
  ): Promise<PrismaAudioFile | null> {
    return this.prisma.audioFile.findUnique(args);
  }
  async createAudioFile(
    args: Prisma.AudioFileCreateArgs
  ): Promise<PrismaAudioFile> {
    return this.prisma.audioFile.create(args);
  }
  async updateAudioFile(
    args: Prisma.AudioFileUpdateArgs
  ): Promise<PrismaAudioFile> {
    return this.prisma.audioFile.update(args);
  }
  async deleteAudioFile(
    args: Prisma.AudioFileDeleteArgs
  ): Promise<PrismaAudioFile> {
    return this.prisma.audioFile.delete(args);
  }
  async GetAudioFileStatus(args: AudioFileFindUniqueArgs): Promise<AudioFile> {
    throw new Error("Not implemented");
  }
  async UploadAudioFile(args: AudioFileCreateInput): Promise<AudioFile> {
    throw new Error("Not implemented");
  }
}
